/*
 * API POC Server
 *
 * This is a proof of concept OpenAPI server
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
	"github.com/awslabs/aws-lambda-go-api-proxy/gorillamux"
	sw "github.com/bhechinger/tunnel_manager/go"
	_ "github.com/bhechinger/tunnel_manager/statik"
	"github.com/rakyll/statik/fs"
	"log"
	"net/http"
)

var gmux *gorillamux.GorillaMuxAdapter

func init() {
	log.Printf("Server cold started")

	router := sw.NewRouter()

	statikFS, err := fs.New()
	if err != nil {
		panic(err)
	}
	staticServer := http.FileServer(statikFS)

	sh := http.StripPrefix("/ui/", staticServer)
	router.PathPrefix("/ui/").Handler(sh)

	//log.Fatal(http.ListenAndServe(":8080", router))
	gmux = gorillamux.New(router)
}

func Handler(req events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	// If no name is provided in the HTTP request body, throw an error
	return gmux.Proxy(req)
}

func main() {
	lambda.Start(Handler)
}
