DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS permission_membership CASCADE;
DROP TABLE IF EXISTS agents CASCADE;
DROP TABLE IF EXISTS routers CASCADE;
DROP TABLE IF EXISTS tunnels CASCADE;
