name: Rust

on:
  push:
    branches: [master]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest

        toolchain:
        - 1.68.1
        - stable
        - nightly

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        profile: minimal
        override: true
        components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v1
      with:
        key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}-${{ matrix.toolchain }}
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: clippy
      run: cargo clippy -- --deny "warnings"
    - name: fmt
      run: cargo fmt -- --check
